FROM jenkins/jenkins:lts-jdk11
USER root
RUN apt update && \
    apt install -y --no-install-recommends \
        gnupg \
        curl \
        ca-certificates \
        apt-transport-https \
        apt-utils \
        software-properties-common \
        black \
        git \
        make \
        maven \
        inetutils-ping && \
    rm -rf /var/lib/apt/lists/*
USER jenkins