FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ARG UNAME=whore
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN mkdir -p /var/lib/apt/lists/partial

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y apt-utils && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        apt-utils \
        software-properties-common \
        python3-pip \
        python3.9 \
        python3.9-dev \
        python3-tabulate \
        black \
        git 

RUN mkdir -p /home/bot/log

RUN groupadd -g $GROUP_ID -o $UNAME
RUN useradd -u $USER_ID -g $GROUP_ID --create-home $UNAME && \
    adduser $UNAME sudo && \
    mkdir /ubuntu && \
    chown $UNAME /ubuntu

COPY requirements.txt /tmp

RUN python3.9 -m pip install --user -r /tmp/requirements.txt
WORKDIR /home/$UNAME
USER $UNAME

